### ISSUE TITLE
Nextflow module for phylo_wgs parse_cnvs

### ISSUE THREAD

**Issue by nikhil** [mskcc/NeoAntigen-Pipeline#11]

**Comment by nikhil** [comment]
Dockerhub Container: mskcc/phylowgs:v1.3-msk
command: python2 /usr/bin/parser/parse_cnvs.py -c 0 -f facets [facets_gene_level_txt]
output: cnvs.txt

**Comment by pintoa1-mskcc** [comment]
https://github.com/mskcc-omics-workflows/modules/tree/feature/neoantigen_parse_cnvs

This completes this issue.
