### ISSUE TITLE
Nextflow module for phylo_wgs create_phylowgs_inputs.py

### ISSUE THREAD

**Issue by nikhil** [mskcc/NeoAntigen-Pipeline#12]

**Comment by nikhil** [comment]
Dockerhub Container: mskcc/phylowgs:v1.3-msk
command: python2 /usr/bin/parser/create_phylowgs_inputs.py --cnvs S1=[cnvs.txt from parse_cnvs] --vcf-type S1=maf S1=[tempo unfiltered.maf]
output: cnvs.txt

**Comment by pintoa1-mskcc** [comment]
this input comes from https://github.com/mskcc/NeoAntigen-Pipeline/issues/11 right?

**Comment by nikhil** [comment]
Resolved with: https://github.com/mskcc-omics-workflows/modules/pull/51
