### ISSUE TITLE
Investigate Neoantigen tools/pipelines

### ISSUE THREAD

**Issue by nikhil** [mskcc/neoantigen-pipeline#6]
There are many neoantigen tools and pipelines out there.

Let's investigate these tools and consider adding them so ours can be the best!

Add all tools/pipelines of interest to the document here:
https://docs.google.com/document/d/11fAqBiD9bKB4pUB79kjiwxL3GzQpzl1852vHlBNRPdU/edit

**Comment by pintoa1-mskcc** [comment]
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-03005-9

For neoantigens from Structural Variants

**Comment by pintoa1-mskcc** [comment]
I dont know if we have anything on agretopicity  (ratio of mutant vs. wild-type peptide binding affinities) but previous tool we used developed by CCS is https://github.com/mskcc/agReto
